### ISSUE TITLE
LogFileParser is unable to parse SPaT log files sent from V2XHub

### ISSUE THREAD

**Issue by paulbourelly999** [usdot-jpo-ode/jpo-ode#433]
### Types of Issue

- [ x ] Anomaly report (something appears to not work correctly)
- [x] Enhancement request (describe the enhancement being requested)
- [ ] Other (please ensure the description clarifies why the issue doesn’t fall into either of the above categories)

### Descriptive summary

When sending a spatTx.bin SPaT log file generated by the V2XHub SPaT Logger Plugin the ODE fails to parse them and prints the following exception.

`ileAsn1CodecPublisher - Publishing file spatTx.bin 
2021-03-23 20:36:24 [pool-7-thread-1] INFO  FileAsn1CodecPublisher - Publishing data from uploads/bsmlog/spatTx.bin to asn1_codec. 
2021-03-23 20:36:24 [pool-7-thread-1] DEBUG LogFileParser - Parsing as "Transmit SPAT" log file type. 
2021-03-23 20:36:24 [pool-7-thread-1] ERROR ImporterProcessor - Failed to open or process file: uploads/bsmlog/spatTx.bin 
us.dot.its.jpo.ode.coder.FileAsn1CodecPublisher$FileAsn1CodecPublisherException: Failed to publish file.
	at us.dot.its.jpo.ode.coder.FileAsn1CodecPublisher.publishFile(FileAsn1CodecPublisher.java:63)
	at us.dot.its.jpo.ode.importer.ImporterProcessor.publishFile(ImporterProcessor.java:135)
	at us.dot.its.jpo.ode.importer.ImporterProcessor.processAndBackupFile(ImporterProcessor.java:97)
	at us.dot.its.jpo.ode.importer.ImporterProcessor.processDirectory(ImporterProcessor.java:63)
	at us.dot.its.jpo.ode.importer.ImporterDirectoryWatcher.lambda$run$0(ImporterDirectoryWatcher.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: us.dot.its.jpo.ode.coder.stream.LogFileToAsn1CodecPublisher$LogFileToAsn1CodecPublisherException: Error parsing or publishing data.
	at us.dot.its.jpo.ode.coder.stream.LogFileToAsn1CodecPublisher.publish(LogFileToAsn1CodecPublisher.java:96)
	at us.dot.its.jpo.ode.coder.FileAsn1CodecPublisher.publishFile(FileAsn1CodecPublisher.java:61)
	... 11 common frames omitted
Caused by: us.dot.its.jpo.ode.importer.parser.FileParser$FileParserException: Error parsing spatTx.bin
	at us.dot.its.jpo.ode.importer.parser.SpatLogFileParser.parseFile(SpatLogFileParser.java:69)
	at us.dot.its.jpo.ode.coder.stream.LogFileToAsn1CodecPublisher.publish(LogFileToAsn1CodecPublisher.java:85)
	... 12 common frames omitted
Caused by: us.dot.its.jpo.ode.importer.parser.FileParser$FileParserException: Error parsing spatTx.bin on step 1
	at us.dot.its.jpo.ode.importer.parser.PayloadParser.parseFile(PayloadParser.java:62)
	at us.dot.its.jpo.ode.importer.parser.LogFileParser.nextStep(LogFileParser.java:150)
	at us.dot.its.jpo.ode.importer.parser.SpatLogFileParser.parseFile(SpatLogFileParser.java:60)
	... 13 common frames omitted
Caused by: us.dot.its.jpo.ode.importer.parser.FileParser$FileParserException: Data size of 28435 is larger than allocated buffer size of 4096
	at us.dot.its.jpo.ode.importer.parser.LogFileParser.parseStep(LogFileParser.java:104)
	at us.dot.its.jpo.ode.importer.parser.PayloadParser.parseFile(PayloadParser.java:52)
	... 15 common frames omitted
2021-03-23 20:36:24 [pool-7-thread-1] ERROR EventLogger - Failed to open or process file: uploads/bsmlog/spatTx.bin 
us.dot.its.jpo.ode.coder.FileAsn1CodecPublisher$FileAsn1CodecPublisherException: Failed to publish file.
	at us.dot.its.jpo.ode.coder.FileAsn1CodecPublisher.publishFile(FileAsn1CodecPublisher.java:63)
	at us.dot.its.jpo.ode.importer.ImporterProcessor.publishFile(ImporterProcessor.java:135)
	at us.dot.its.jpo.ode.importer.ImporterProcessor.processAndBackupFile(ImporterProcessor.java:97)
	at us.dot.its.jpo.ode.importer.ImporterProcessor.processDirectory(ImporterProcessor.java:63)
	at us.dot.its.jpo.ode.importer.ImporterDirectoryWatcher.lambda$run$0(ImporterDirectoryWatcher.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: us.dot.its.jpo.ode.coder.stream.LogFileToAsn1CodecPublisher$LogFileToAsn1CodecPublisherException: Error parsing or publishing data.
	at us.dot.its.jpo.ode.coder.stream.LogFileToAsn1CodecPublisher.publish(LogFileToAsn1CodecPublisher.java:96)
	at us.dot.its.jpo.ode.coder.FileAsn1CodecPublisher.publishFile(FileAsn1CodecPublisher.java:61)
	... 11 common frames omitted
Caused by: us.dot.its.jpo.ode.importer.parser.FileParser$FileParserException: Error parsing spatTx.bin
	at us.dot.its.jpo.ode.importer.parser.SpatLogFileParser.parseFile(SpatLogFileParser.java:69)
	at us.dot.its.jpo.ode.coder.stream.LogFileToAsn1CodecPublisher.publish(LogFileToAsn1CodecPublisher.java:85)
	... 12 common frames omitted
Caused by: us.dot.its.jpo.ode.importer.parser.FileParser$FileParserException: Error parsing spatTx.bin on step 1
	at us.dot.its.jpo.ode.importer.parser.PayloadParser.parseFile(PayloadParser.java:62)
	at us.dot.its.jpo.ode.importer.parser.LogFileParser.nextStep(LogFileParser.java:150)
	at us.dot.its.jpo.ode.importer.parser.SpatLogFileParser.parseFile(SpatLogFileParser.java:60)
	... 13 common frames omitted
Caused by: us.dot.its.jpo.ode.importer.parser.FileParser$FileParserException: Data size of 28435 is larger than allocated buffer size of 4096
	at us.dot.its.jpo.ode.importer.parser.LogFileParser.parseStep(LogFileParser.java:104)
	at us.dot.its.jpo.ode.importer.parser.PayloadParser.parseFile(PayloadParser.java:52)
	... 15 common frames omitted
2021-03-23 20:36:24 [pool-7-thread-1] INFO  ImporterProcessor - File moved to failure directory: uploads/failed `

### ODE version where this issue was discovered

1.2.1
### Expected behavior
ODE should be able to parse SPaT log files generated by the V2XHub SPAT Logger plugin.
### Actual behavior

ODE throws exceptions when attempting to parse SPaT log file generated by the V2XHub SPAT Logger plugin.
### Steps to reproduce the actual behavior

1. Build image of origin/SPaT_log_files branch of V2XHub locally
2. Run image and copy bsmwatchscript.sh and ODE.pem into container at /var/log/tmx and install install rsync and inotify-tools on v2xhub container
3. Build and run ODE image on AWS instance
4. Edit bsmwatchscript.sh with AWS instance ip address
5. Run bsmwatchscript.sh
6. Configure SPATLoggerPlugin to generate SPaT log files with the following name : spatTx
7.  Use bsmscript.py to send SPAT message to V2XHub Message Receiver plugin.
8. This should trigger SPATMessageLogger plugin to generate a new SPat log file, which should be caught and sent by the bsmwatchscript.sh to the AWS ODE instance. Then check the ODE container logs.

**Comment by paulbourelly999** [comment]
ZIP includes scripts and log file
[bsmwatchscript.zip](https://github.com/usdot-jpo-ode/jpo-ode/files/6192842/bsmwatchscript.zip)

**Comment by dan-du-car** [comment]
Issue is closed as the PR is merged.
